# Generated by Django 4.1 on 2022-10-01 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Counsellor",
            fields=[
                (
                    "counsellorID",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("languages", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
                ("images", models.ImageField(upload_to="counsellorImage")),
                ("address", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("aid", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("completed", models.BooleanField()),
                (
                    "counsellorID",
                    models.ForeignKey(
                        db_column="counelloerID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.counsellor",
                    ),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
