# Generated by Django 4.1 on 2022-09-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Appointment",),
        migrations.DeleteModel(name="Counsellor",),
    ]
